"""initial_schema21

Revision ID: 4ecece073684
Revises: ebaba2fc40a7
Create Date: 2026-02-12 23:56:25.446803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ecece073684'
down_revision: Union[str, None] = 'ebaba2fc40a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mandi_farmer_orders', sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('retailer_mandi_order', sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('retailer_mandi_order', 'quantity')
    op.drop_column('mandi_farmer_orders', 'quantity')
    # ### end Alembic commands ###
