"""initial_schema

Revision ID: ebaba2fc40a7
Revises: 
Create Date: 2026-02-12 23:12:02.090188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebaba2fc40a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'severity')
    op.add_column('mandi_farmer_orders', sa.Column('src_lat', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('mandi_farmer_orders', sa.Column('src_long', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('mandi_farmer_orders', sa.Column('dest_lat', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('mandi_farmer_orders', sa.Column('dest_long', sa.Numeric(precision=10, scale=7), nullable=True))
    op.drop_column('mandi_farmer_orders', 'source')
    op.drop_column('mandi_farmer_orders', 'destination')
    op.add_column('retailer_mandi_order', sa.Column('src_lat', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('retailer_mandi_order', sa.Column('src_long', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('retailer_mandi_order', sa.Column('dest_lat', sa.Numeric(precision=10, scale=7), nullable=True))
    op.add_column('retailer_mandi_order', sa.Column('dest_long', sa.Numeric(precision=10, scale=7), nullable=True))
    op.drop_column('retailer_mandi_order', 'source')
    op.drop_column('retailer_mandi_order', 'destination')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('retailer_mandi_order', sa.Column('destination', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('retailer_mandi_order', sa.Column('source', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('retailer_mandi_order', 'dest_long')
    op.drop_column('retailer_mandi_order', 'dest_lat')
    op.drop_column('retailer_mandi_order', 'src_long')
    op.drop_column('retailer_mandi_order', 'src_lat')
    op.add_column('mandi_farmer_orders', sa.Column('destination', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('mandi_farmer_orders', sa.Column('source', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.drop_column('mandi_farmer_orders', 'dest_long')
    op.drop_column('mandi_farmer_orders', 'dest_lat')
    op.drop_column('mandi_farmer_orders', 'src_long')
    op.drop_column('mandi_farmer_orders', 'src_lat')
    op.add_column('alerts', sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
